# Assignment-5


### Problem-1

In a network, data packets are sent through a shared channel. Suppose there are 10 devices attempting to send data. In any given time slot, each device has a 20% chance of attempting to send a packet, independently of other devices. A collision occurs if two or more devices attempt to send a packet in the same time slot. What is the probability that in a given time slot, there will be no collisions?

###### Each devide send the data with change of 20% i.e p =0.2
###### y is the devides which tries to send data 
###### collision occures if y>=2
###### no collision y=0 or y =1
###### Binomial y ~ Binomial(n=10, p=0.2)
Formula
$$
P(X=k) = \binom{n}{k} p^k (1-p)^{n-k}
$$



1.Exacly one devide send data k=1

$$
P(X=1) = \binom{10}{1} {0.2}^1{0.8}^9 = 10.0.2.0.13421= 0.268435
$$

2. No decide send data4
$$
P(x=0) =\binom{10}{0} {0.2}^0{0.8}^10 = 1.1.0.107374 = 0.107374
$$

p = p(y=0)+ p(y=1)
 p = 0.268435 + 0.10.7374

= =0.375809

In [1]:
import numpy as np
import math

n  =10
p = 0.2
q = 1-p

# probability 1 device send
p0 = q ** n

# 1 devide send data

p1 = math.comb(n,1) * (p ** 1) * (q ** (n-1))

# no collision

p_no_collisoin = p0 + p1

print("probability of no colision", p_no_collisoin)





probability of no colision 0.3758096384000002


### Problem-2

A system uses 8-character passwords. Each character can be any lowercase letter (a-z), uppercase letter (A-Z), or digit (0-9).
What is the probability that a randomly generated 8-character password contains at least one digit, given that character repetition is allowed?

In [12]:
import numpy as np
import math

# number of characters 
# small - 26
# big - 26
# numbers - 10
# total -62

n = 62
p_length = 8
letters_l = 52



np_digits = (letters_l/n) ** p_length
p_one_digit = 1 - np_digits
print("probabiloty of one digit", p_one_digit)


probabiloty of one digit 0.7551538761591853


### Problem-3

A software project has two modules, A and B. The probability that module A has a bug is 0.15, and the probability that module B has a bug is 0.10. The probability that both modules have bugs is 0.03.

(a) What is the probability that module A has a bug, given that module B has a bug?

(b) What is the probability that module B has a bug, given that module A does not have a bug?

P(A∣B)=
P(B)
P(A∩B)
	​


In [17]:
import numpy as np
import math

p_A = 0.15
p_B = 0.10
both_AB = 0.03

p = both_AB/0.10

# /0.10

print(p)

# (b) P(B | A^c)
P_A_not = 1 - p_A
P_B_and_A_not = p_B - both_AB
P_B_given_A_not = P_B_and_A_not / P_A_not

print("P(A | B) =", p)
print("P(B | A not) =", P_B_given_A_not)


0.3
P(A | B) = 0.3
P(B | A not) = 0.0823529411764706


### Problem-4

A robot uses a sensor to detect an obstacle. The sensor has a 95% chance of correctly detecting an obstacle when one is present (true positive rate). However, it also has a 2% chance of indicating an obstacle when there isn't one (false positive rate).
In the robot's environment, obstacles are present 10% of the time.

What is the probability that an obstacle is truly present, given that the sensor indicates an obstacle?

### Problem-5

A spam filter uses a keyword "money" to identify spam emails.
- 10% of all emails are spam.
- If an email is spam, the word "money" appears in it 80% of the time.
- If an email is not spam, the word "money" appears in it 5% of the time.

If an email contains the word "money", what is the probability that it is spam?

##### s = email spam
##### m = mail contains the word money

##### probability
##### p(s) = 0.10
##### p(m|s)  0.80
##### np_spam = 0.05 ( no spam)

##### need to identify spam given momney

###### P(S∣M)=
P(M)
P(M∣S)P(S)
	​


In [19]:
# 10% emails are spam
sp = 0.10
# spam email 80%
spm =0.80
# if mail is not spam 
not_spam = 0.5

# total probability of money 
non_spam = 1-sp
total_p_money = (spm * sp) + (not_spam * non_spam)
print("Total money':",
      total_p_money)
# Bayes theorm

p_given_money  = (spm * sp)/total_p_money

print("Probability email is spam given it contains 'money':",
      p_given_money)



Total money': 0.53
Probability email is spam given it contains 'money': 0.15094339622641512


### Problem-6

A rare disease affects 1 in 10,000 people. A diagnostic test for this disease has a 99% true positive rate (correctly identifies the disease when present) and a 0.5% false positive rate (incorrectly indicates the disease when not present).

If a randomly selected person tests positive for the disease, what is the probability that they actually have the disease?

n = 10000
D = 0.0001
test = 0.99
true_P = 0.99
false_negative  =0.005
p_not_having_d = 1-0.0001 = 0.9999

$P(D \mid TP+) = \frac{P(TP+ \mid D)\,P(D)}{P(TP+)}$


In [24]:
n = 1/10000
no_desease = 1-n
postitive_t = 0.99
false_postive = 0.005

false_negative  =0.005
p_not_having_d = 0.005

# desease postitive probability
total_p_positive = (postitive_t * n + false_negative * no_desease)

print("probabiloty of positive", total_p_positive)

p_desease  = (postitive_t * n)/total_p_positive


print("probabiloty of person having positive desease", p_desease)

probabiloty of positive 0.005098500000000001
probabiloty of person having positive desease 0.019417475728155338


### Problem-7

A batch of 500 microchips is produced. The probability that a single microchip is defective is 0.02.
Let X be the number of defective microchips in a random sample of 20 microchips from this batch. Assume the sample is taken with replacement, or the batch is large enough that we can model this as independent trials.

(a) What is the probability that exactly 3 microchips in the sample are defective?
(b) What is the probability that at least 2 microchips in the sample are defective?

###### no of microchipd- 500
###### microchip_singleerror - 0.02
###### x_defectivechip_per 20 
###### 2 mic defective 10 -0.2 

#### Binomial formula

$$
P(X=k) = \binom{n}{k} p^k (1-p)^{n-k}
$$

In [29]:
import math

n = 20
p = 0.02

# (a) Exactly 3 defective
prob_3 = math.comb(n, 3) * (p**3) * ((1 - p)**(n - 3))

# (b) At least 2 defective
prob_0 = (1 - p)**n
prob_1 = math.comb(n, 1) * p * ((1 - p)**(n - 1))
prob_at_least_2 = 1 - prob_0 - prob_1

print("P(X = 3) =", prob_3)
print("P(X ≥ 2) =", prob_at_least_2)


P(X = 3) = 0.006469014507567489
P(X ≥ 2) = 0.059898978548948933


### Problem-8

The time (in hours) until a critical server component fails follows an exponential distribution with a mean of 500 hours.

(a) What is the probability that the component will last between 400 and 600 hours?

(b) The component has already been running for 300 hours without failure. What is the probability that it will last for at least another 250 hours?

####### total_hours = 500

#### mean
 
##### no_error = 300

##### probability 200/500 =0.4

2. 0.5

In [30]:
import math

lam = 1 / 500

# (a)
prob_between = math.exp(-lam * 400) - math.exp(-lam * 600)

# (b)
prob_additional = math.exp(-lam * 250)

print("P(400 ≤ T ≤ 600) =", prob_between)
print("P(T > 250 | already ran 300) =", prob_additional)


P(400 ≤ T ≤ 600) = 0.14813475220501943
P(T > 250 | already ran 300) = 0.6065306597126334


### Problem-9

The noise in a sensor's reading can be modeled by a Gaussian (Normal) distribution with a mean of 0 (bias) and a standard deviation of 0.5 units.

(a) What is the probability that a sensor reading's noise is between -0.2 and 0.3 units?

(b) If a reading is considered an "outlier" if its noise is more than 1.5 standard deviations away from the mean, what is the probability that a random reading is an outlier?

### Problem-10

The latency (delay) in a specific network segment is observed to be normally distributed with a mean of 150 ms and a standard deviation of 20 ms.

(a) What is the probability that a data packet experiences a latency greater than 180 ms?

(b) Due to new QoS (Quality of Service) requirements, 90% of packets must arrive within a certain latency threshold. What is this threshold (in ms)?

(c) If a network engineer defines "critical latency" as any latency exceeding 2.5 standard deviations above the mean, what is the probability that a packet experiences critical latency?

In [1]:
from scipy.stats import norm

mu = 150
sigma = 20

prob_a = 1 - norm.cdf(180, mu, sigma)
print(prob_a)


threshold_b = norm.ppf(0.90, mu, sigma)
print(threshold_b)

prob_c = 1 - norm.cdf(200, mu, sigma)
print(prob_c)


0.06680720126885809
175.631031310892
0.006209665325776159


### Problem-11

The lifespan of a certain electronic component, due to manufacturing variations, is normally distributed with a mean of 2500 hours and a standard deviation of 300 hours.

(a) A customer requires components that last at least 2000 hours. What percentage of manufactured components meet this requirement?

(b) The manufacturer wants to provide a warranty such that only 1% of components fail before the warranty period ends. What should be the warranty period (in hours)?

(c) If a batch of 10,000 components is produced, how many components are expected to have a lifespan between 2200 and 2800 hours?

\(z=\frac{x-\mu }{\sigma }=\frac{2000-2500}{300}=-1.6667\)

## Problem Statement

#### Electronic Component Lifespan Analysis

**Parameters:**
* Mean ($\mu$): 2500 hours
* Standard Deviation ($\sigma$): 300 hours

---

#### (a) Percentage of components lasting $\ge 2000$ hours

1. **Calculate the Z-score:**
   $$z = \frac{x - \mu}{\sigma} = \frac{2000 - 2500}{300} = -1.67$$

2. **Find the probability:**
   Using the standard normal table, $P(Z < -1.67) \approx 0.0475$.
   Since we need "at least" 2000 hours:
   $$P(Z \ge -1.67) = 1 - 0.0475 = 0.9525$$

**Result:** Approximately **95.25%** of components meet the requirement.

---

#### (b) Warranty period for 1% failure rate

We need to find the value $x$ where the area to the left is $0.01$.

1. **Find the Z-score for 1%:**
   From the Z-table, the area of $0.01$ corresponds to $z \approx -2.326$.

2. **Solve for $x$:**
   $$x = \mu + z\sigma$$
   $$x = 2500 + (-2.326 \times 300) = 1802.2$$

**Result:** The warranty period should be set to **1,802.2 hours**.

---

#### (c) Expected components between 2200 and 2800 hours

1. **Calculate Z-scores:**
   * For 2200: $z_1 = \frac{2200 - 2500}{300} = -1.0$
   * For 2800: $z_2 = \frac{2800 - 2500}{300} = 1.0$

2. **Calculate Probability:**
   According to the Empirical Rule (68-95-99.7), the area between $\pm 1\sigma$ is approximately **0.6827**.

3. **Calculate Expected Value:**
   $$E = 10,000 \times 0.6827 = 6,827$$

**Result:** Approximately **6,827 components** are expected to fall in this range.



In [3]:
from scipy.stats import norm

mu = 2500
sigma = 300

prob_a = 1 - norm.cdf(2000, mu, sigma)
print(prob_a)

warranty_b = norm.ppf(0.01, mu, sigma)
print(warranty_b)

prob_c = norm.cdf(2800, mu, sigma) - norm.cdf(2200, mu, sigma)
expected_c = 10000 * prob_c

print(prob_c)
print(expected_c)


0.9522096477271853
1802.0956377877478
0.6826894921370859
6826.894921370858


### Problem-12
The probability density function (pdf) of the triangular distribution is characterized by three points as shown in the figure below.

<img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Triangular_distribution_PMF.png" alt="triangular distribution" width="500"/>

(a) min value of the distribution,
(b) max value of the distribution, and
(c) mode of the distribution

Note: $a \leq c \leq b$

Create a class `TriangularDistribution` with attributes `min`, `max` and `mode`. You need to implement the following methods:

- `pdf(x)`: returns the value of the pdf at point $x$.
- `plot_pdf()`: plots the pdf in the range $[min , max]$
- `cdf(x)`: returns the value of the cdf at point $x$ ; which denotes $P(X \leq x)$
- `plot_cdf()`: plots the cdf in the range $[min , max]$
- `get_probability(x1, x2)`: returns the probability $P(x_1 \leq X \leq x_2)$, where $x_1 \lt x_2$.

Gracefully handle the possible errors and also the edge conditions when either $ a = c $ or $b = c$ in the distribution.

Test your implementation.

In [ ]:
### Write your code here


### Problem-13

The `rand5()` function which returns a uniform random integer within the range [1, 5], is defined as following:

```python
def rand5():
    import numpy as np
    return np.random.randint(1,6)
```

Write a function `rand7()` that will generate a uniform random integer within the range [1, 7] by only using `rand5()`. 

Note: You can call `rand5()` as many time as you want inside the function `rand7()`, but you can not use `np.random.randint(1, 8)` or any other built-in methods in python. 

In [3]:
### Write your code here
import numpy as np
def rand5(): 
    return np.random.randint(1,6)



def rand7():
    while True:
        # Generate a number from 1 to 25
        num = (rand5() - 1) * 5 + rand5()  # uniform in [1, 25]

        # Use only 1..21 to keep uniformity
        if num <= 21:
            result = (num - 1) % 7 + 1
            return result
        
        print(result)



### Problem-14

A grayscale image can be represented as a matrix where the dimensions are (height, width). 
Let's consider a simplified scenario with two grayscale images, $A$ and $B$, both represented as 10×10 matrices where each element represents pixel intensity. Pixel intensity is an integer in the range [0-255].

You want to create a blended image $C$ by combining $A$ and $B$ such that $C=w_1 A+w_2 B$. This represents a weighted average blend.
Note that each element in the resultant matrix $C$ should also fall within the range [0, 255]. 

write the code of the function `blend_images(image_A, image_B, weight_A, weight_B)` that takes two matrices and two scalar weights and produces another matrix as an output by performing the above operation.

In [4]:
### Write your code here
import numpy as np

def blend_images(image_A, image_B, weight_A, weight_B):
    # Convert inputs to numpy arrays
    A = np.array(image_A, dtype=float)
    B = np.array(image_B, dtype=float)
    
    # Weighted blending
    C = weight_A * A + weight_B * B
    
    # Clip values to stay within [0, 255]
    C = np.clip(C, 0, 255)
    
    # Convert back to integer pixel values
    return C.astype(np.uint8)


In [ ]:
A = np.random.randint(0, 256, (10, 10))
B = np.random.randint(0, 256, (10, 10))

C = blend_images(A, B, 0.6, 0.4)
print(C)


[[124 178 204 105  58 185 110 152  71 108]
 [170 146  72 113 140 143  97 123 250 114]
 [107  92 111 113 221 189 214  65 241  85]
 [ 89  83 108 186 175  67  75  57  33 125]
 [ 28 157 153 133  84 195 164 101 113 155]
 [ 52  60 152  49 199  94 140  66 183 209]
 [195 123 183 151 104  14 199 178 101 216]
 [ 12 158  29 236  48  80 106 204  44  51]
 [119 213  27  50 158  76 150 105   2 158]
 [124 107 142  76 109 126 155 198 105 161]]


: 

### Problem-15

Calculate the eigen values and eigen vectors of the following matrices.

$A = \begin{bmatrix}
5 & 2 \\
2 & 2
\end{bmatrix}$      

$B = \begin{bmatrix}
1 & 1 & 0\\
0 & 2 & 0\\
-1 & 1 & 3
\end{bmatrix}$

In [27]:
import numpy as np

A = np.array([[5,2],[2,2]])
B = np.array([[1,1,0],[0,2,0],[-1,1,3]])

eig_A = np.linalg.eig(A)
eig_B = np.linalg.eig(B)

print("Eigenvalues of A:", eig_A[0])
print("Eigenvectors of A:\n", eig_A[1])

print("\nEigenvalues of B:", eig_B[0])
print("Eigenvectors of B:\n", eig_B[1])

Eigenvalues of A: [6. 1.]
Eigenvectors of A:
 [[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

Eigenvalues of B: [3. 1. 2.]
Eigenvectors of B:
 [[0.         0.89442719 0.70710678]
 [0.         0.         0.70710678]
 [1.         0.4472136  0.        ]]
